### ISSUE TITLE
'smaller' broken in scribble/jfp

### ISSUE THREAD

**Issue by bennn** [racket/scribble#103]
### Example Program

```
;; file.scrbl
#lang scribble/jfp

@title{Hello}

If you give a @smaller{mouse} a cookie.
```

### Output

- `scribble --pdf file.scrbl` explodes 
- `scribble --latex file.scrbl; pdflatex file` outputs "! Undefined control sequence. `\Smaller #1->\textsmaller`"

Changing the language to `scribble/manual` and running `scribble --pdf file.scrbl` generates a pdf.

### Problem

The trouble is that `textsmaller` is defined by the LaTeX [`relsize`](https://www.ctan.org/pkg/relsize?lang=en) package.
Documents produced by `scribble/jfp` currently don't use the `relsize` package, see:
https://github.com/racket/scribble/commit/0ca977aecd6995690bd7744829abe24dd9d12b5d

### Ideas

- Maybe there's nothing wrong with `relsize`
- Maybe it's okay to import just `textsmaller` etc. from `relsize`
- Maybe there's another way to make `smaller` text

**Comment by rfindler** [comment]
My memory was that scribble/jfp just didn't work without that commit. But I guess you're saying that that isn't the case for you?

What LaTeX are you using?

**Comment by rfindler** [comment]
(looks like I have TeXLive-2016)

**Comment by bennn** [comment]
I have TeXLive-2015, and yes if I remove `@smaller` in the sample document then `scribble/jfp` works fine with that TeXLive.

**Comment by rfindler** [comment]
I meant the commit. Your comment "Maybe there's nothing wrong with relsize" seems to suggest you removed the commit and that scribble/jfp can generate a document for you. This isn't what I recall, but maybe something is different about our tex setups.

**Comment by bennn** [comment]
oh right, my bad ... if I add `\usepackage{relsize}` then I'm able to use `scribble/jfp` no problem. By "no problem" I mean that I can render:
1.  the example above, without `@smaller`
2. the example above, with `@smaller`
3. the larger example I mentioned in 0ca977a

(I know that's not exactly removing the commit, but I expect removing it would have the same result.)

Tomorrow I will try upgrading to TexLive 2016.

**Comment by rfindler** [comment]
Thanks Ben. I think I know what paper motivated me to make this commit so I
can revisit that too.

**Comment by rfindler** [comment]
Okay, just to confirm the reason I pushed the commit https://github.com/racket/scribble/commit/0ca977aecd6995690bd7744829abe24dd9d12b5d,

with this tmp.scrbl:

```
#lang scribble/jfp

@title{Hello}

If you give a mouse a cookie.
```
then running `scribble --latex tmp.scrbl` and then running latex on the output, this is the error message.

```
(/usr/local/texlive/2016/texmf-dist/tex/latex/relsize/relsize.sty
! Undefined control sequence.
<argument> \@xvpt 
                  
l.223 \@tempa\Large
                   
? x
No pages of output.
Transcript written on tmp.log.
```

**Comment by bennn** [comment]
Wow, okay. I had the same problem too with `\xvpt`.

To fix, I saved a copy of [`relsize.sty`](https://www.ctan.org/pkg/relsize?lang=en) to my project's folder and commented out line 223 (the one that says `\@tempa\Large`).

When I tested my example program above, I happened to be in the same folder. That's why I was able to `\usepackage{relsize}` --- I was using a different `relsize`. With the original `relsize` I get the same error.

- - -

@rfindler can you try my example file on the latest Scribble commit with this `texstyle.tex`:

```
\renewcommand{\Large}{}
\usepackage{relsize}
```

Works for me, with the command `scribble --pdf ++style texstyle.tex file.scrbl`

In the meantime I guess I will try to make a small example using `jfp.cls` and email the JFP guys. (I didn't see anything in the documentation about `\xvpt` or even `\Large`)

**Comment by bennn** [comment]
Here's a small example:

```
\documentclass{jfp1}
%\renewcommand{\Large}{}
\usepackage{relsize}
\begin{document}
\maketitle
hello
\end{document}
```

1. Download [`jfp1.cls`](ftp://ftp.cambridge.org/pub/texarchive/journals/latex/jfp-cls/jfp1.cls)
2. Run `pdflatex tmp.tex`, it should error
3. Uncomment line 2, run `pdflatex tmp.tex`, it should not error

**Comment by rfindler** [comment]
This suggests a much better fix than what I did!

**Comment by mfelleisen** [comment]
@bennn This does not mean jfp1 cls is broken but incompatible with a package that probably postdates it. I have filed a suggestion anyways.

**Comment by rfindler** [comment]
@mfelleisen I think it means that contacting JFP and asking them for a fix is reasonable, however. Relatedly, I went to this web page at JFP:

https://www.cambridge.org/core/journals/journal-of-functional-programming/information/instructions-contributors

where it says " This, along with related files, can be obtained using anonymous FTP." and gives a link. But that link required a password. So I wasn't able to double check what @bennn is saying.

I don't think waiting for me is required, however. Ben outlines what seems like the right fix to me. Push away.

**Comment by mfelleisen** [comment]
@rfindler As I said, I sent an email already

**Comment by bennn** [comment]
The "official fix" from Cambridge University Press is to create this style file and `\usepackage{Ben-patch}` at the top of documents:

```
%% Created by TexSupport 2nd May 2017 %%
%% 
%% 
\def\@xvpt{15}
%
\endinput
```

I thought it would be possible to just put the `\def` in Scribble's [jfp replacements file](https://github.com/racket/scribble/blob/master/scribble-lib/scribble/jfp/replacements.tex), but I after some failed attempts I think it really needs to be a `\usepackage`.

- - -

> @bennn This does not mean jfp1 cls is broken but incompatible with a package that probably postdates it. 

Okay. Still, I'm suspicious it's a typo because the older [`jfp.cls`](https://raw.githubusercontent.com/liamoc/outside-in/master/tex/reportA/jfp.cls) has the line:

```
\newcommand\Large{\@setfontsize\Large\@xivpt{18}}
```

and the newer [`jfp1.cls`](https://raw.githubusercontent.com/lkuper/dissertation/master/latex_common/jfp1.cls) instead uses `xvpt`

```
\newcommand\Large{\@setfontsize\Large\@xvpt{18}}
```

Changing the newer classfile to use `xivpt` makes the problem go away.

**Comment by mfelleisen** [comment]
Wait, they replied to you?

**Comment by bennn** [comment]
yes

**Comment by bennn** [comment]
... the fix I propose in #104 suggests to me that `jfp1.cls` is not broken.

**Comment by mfelleisen** [comment]
@bennn @rfindler 

The actual response is: 

> We want papers to look uniform, and to benefit from professional design.
> We don't want the design to be spoiled, and as such we do not want relsize to be supported.
>

**Comment by rfindler** [comment]
I don't think relsize is the only way to break those constraints and anyway, probably what they don't want is differently sized text in submissions. The relsize package is just one of many ways to do that.

We could go along by making `smaller` (etc) raise errors in #lang scribble/jfp (with citation to some style guideline they produce), or we could ignore that contraint and make it work.

Either way seems good to me!

**Comment by bennn** [comment]
Yeah, `relsize` is not important. That's just how I found out `\Large` is a problem.

I understand the reason behind the official response, but it's confusing that `{\Large hello}` is an error and `{\LARGE hello}` renders bigger-than-normal text.

(I think `scribble/jfp` should support `smaller` and friends from `scribble/base`. No errors.)

**Comment by mfelleisen** [comment]
I told JFP to develop a documentation that explains why/what and what authors should avoid.
