### ISSUE TITLE
updating acmart.cls

### ISSUE THREAD

**Issue by bennn** [racket/scribble#106]
cc @LeifAndersen 

Problem:
1. the true `acmart.cls` sometimes changes (<https://github.com/borisveytsman/acmart>)
2. the `scribble/acmart` folder keeps a copy of `acmart.cls` in version control

Proposed solution: do what `scribble/jfp` does, and
- remove `acmart.cls` from version control
- add code to check whether `scribble/acmart/acmart.cls` exists, and if not re-download it

Is there any reason to not do this?

- - -

(It would be good to have a way of detecting changes in `borisveytsman/acmart` and automatically updating, but this at least this way you can delete your `acmart.cls` to get a new one.)

**Comment by LeifAndersen** [comment]
Hmm...actually, I wonder if we can even have `acmart.cls` in version control due to copyright concerns.

It really should be downloaded by the library, like other scribble packages.

**Comment by dvanhorn** [comment]
I think downloading is the right thing to do, but just to add another wrinkle: `acmart.cls` is itself generated.  If you want to use the source code from Boris, you'll need to run `latex acmart.ins` to generate `acmart.cls`.  The real source file is `acmart.dtx`.

**Comment by bennn** [comment]
Working on this now, I think I will use this URL:
http://www.sigplan.org/sites/default/files/acmart/current/acmart.cls

And make a note in the docs about the GitHub repo and how to build & use that `acmart.cls`.

Sounds ok?

**Comment by jsmaniac** [comment]
@bennn This will prevent building such documents on the pkg-build server (builds are run without network access). AFAIK there is no "list of files to be downloaded" or an equivalent mechanism in `info.rkt` (for now).

I guess packages which include an `acmart` document will be pretty rare, though, but embedding research articles with implementation packages and vice versa should be something to encourage, not prevent.

**Comment by samth** [comment]
In addition to what @jsmaniac says, I believe that we can distribute acmart.cls just fine (it's available under the Latex Public License, which says that redistribution is ok).

**Comment by bennn** [comment]
Then #108 is unnecessary, and we should just keep `acmart.cls` up-to-date manually?

**Comment by jsmaniac** [comment]
@bennn Maybe we could keep a local copy, and try to update it (if the update fails, proceed with the already-downloaded copy). Would it be difficult/problematic to do so?

**Comment by bennn** [comment]
But, when is a good time to update? Every time `scribble/acmart` renders a document?

I'm thinking manual updates will be easier, but we can keep the note from #108 about how to change `acmart.cls` yourself.

**Comment by jsmaniac** [comment]
A nice solution would be for `raco pkg update` to try to download the new version of `acmart.cls`, but I'm not sure if there is an `update` hook for that purpose.

**Comment by bennn** [comment]
I like the `update` idea.

Related: @samth @stamourv is there a "deploy" script we could edit to update `acmart.cls` just before a release?

**Comment by rfindler** [comment]
You could set up a script that would poll the acmart.cls and, when the hash changes, push a change to the repo (which would trigger an update to the pkg). Probably good to include version numbers with those changes some of the times, so you may want a manual step.
