### ISSUE TITLE
Multiple history elements difficult to read

### ISSUE THREAD

**Issue by jackfirth** [racket/scribble#114]
The `history` form puts multiple changes / additions together into a single paragraph. This can be difficult to read when looking for changes associated with a particular version or set of versions, especially with the smaller font. I'd find it more readable if individual additions / changes were each on their own line, such as what happens when you use one `history` form per change instead of a single `history` form. The [`history` documentation](https://docs.racket-lang.org/scribble/Version_History.html?q=history#%28form._%28%28lib._scribble%2Fmanual..rkt%29._history%29%29) has a good example of the problem.

**Comment by mfelleisen** [comment]
You can easily accomplish this with `@nl` a `newline` macro and some basic discipline: 

```
@history[
 #:changed "1.8" @list{Tue Mar 21 12:12:50 EDT 2017 garbled sentence from Ron Garcia
 @nl}
 #:changed "1.7" @list{Thu Feb 11 10:21:44 EST 2016 typos from Marc Kaufmann
 @nl}
 #:changed "1.6" @list{Thu Nov  5 21:27:20 EST 2015 feedback, typos from
 @nl @hs Thomas Wahl
 @nl}
 #:changed "1.5" @list{Sun Sep 20 15:24:08 EDT 2015 added @secref{trinity},
 @nl
 @hs fixed the description of Waterloo's curriculum
 @nl}
...
 #:changed "1.1" @list{Wed Sep 16 21:59:11 EDT 2015:
typos and feedback from 
@nl @hs Tony Garnock-Jones,
@nl @hs Therapon Skotiniotis, 
@nl @hs Shriram Krishnamurthi,
@nl @hs Matthew Flatt, 
@nl @hs Vincent St-Amour,
@nl @hs Karl Lieberherr
@nl @hs Nick Shelley 
@nl
}

 #:changed "1.0" @list{Wed Sep 16 15:07:49 EDT 2015: initial release @nl}
]
```

See [http://www.ccs.neu.edu/home/matthias/Thoughts/Growing_a_Programmer.html](url) for how this renders.

**Comment by jackfirth** [comment]
Do you have a suggestion for how to get that to work with `#:added` statements as well?

**Comment by mflatt** [comment]
I don't think that adding explicit newlines is a good idea; the formatting should be up to `history`. I'd be happy with a change to `history` to put each entry on its own line, though.

**Comment by mfelleisen** [comment]
[Correct. Patterns ought to be eliminated, and in this case, it’s history’s turn to be changed.]
