### ISSUE TITLE
#lang scribble/acmart in various "simple" forms doesn't work quite right

### ISSUE THREAD

**Issue by rfindler** [racket/scribble#121]
1) This program (in the file `x.scrbl`):

```
#lang scribble/acmart
```

when run via `scribble --pdf x.scrbl` produces this latex error:

```
! LaTeX Error: \SAuthorinfo undefined.
```

2) This program:

```
#lang scribble/acmart
@author{me}
```

when run as before produces an empty pdf file.

For the record, I don't think it is necessary that these scribble programs produce something useful, if that's hard. A helpful error message saying what needs to be done would be just great.

**Comment by bennn** [comment]
c4b4e4c92951cc5f827c718467dbe119839004dc
