### ISSUE TITLE
table-of-contents in scribble/acmart

### ISSUE THREAD

**Issue by rfindler** [racket/scribble#125]
When I run this program:

```
#lang scribble/acmart @acmsmall
@title{title}
@subtitle{x}
@author{me}
@table-of-contents[]
@section{Introduction}
```

via `scribble --pdf x.scrbl`, It produces the following latex error (I think this is the relevant except from the output, anyway)

```
! Missing \endcsname inserted.
<to be read again> 
                   \@@par 
l.511 \newpage \tableofcontents
                                \newpage
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

```

**Comment by bennn** [comment]
Oh wow,
- `scribble --latex x.scrbl; pdflatex foo.tex` works,
- but `scribble --latex x.scrbl; pdflatex foo.tex; pdflatex foo.tex` errors  (with `! Missing \endcsname inserted.`)

**Comment by rfindler** [comment]
sounds like an issue to raise on the acmart.cls repo? :)

**Comment by bennn** [comment]
Yes! https://tex.stackexchange.com/questions/378547/using-tocstyle-with-acm-acmart-style

For `scribble/acmart` for now, we could stop using `tocstyle.sty`
