### ISSUE TITLE
Using make-eval-factory to include Typed Racket modules

### ISSUE THREAD

**Issue by lexi-lambda** [racket/scribble#13]
I’ve come across some odd behavior when using make-eval-factory from scribble/eval to include Typed Racket modules in the produced evaluators. Specifically, TR complains about macros “from typed module used in untyped code”. This is probably best explained via example, so here’s a minimal version of the example I ran into that produces the problem:

``` racket
#lang scribble/manual

@(require scribble/eval)

@(examples
  #:eval ((make-eval-factory #:lang 'typed/racket/base
                             '(typed/alexis/util/comparator)))
  (struct foo ())
  (: foo-compare (foo foo -> (U -1 0 1)))
  (define (foo-compare a b) 0)
  (define-comparison-predicates foo : foo foo-compare)
  (foo=? (foo) (foo)))
```

```
Type Checker: Macro define-comparison-predicates from typed module used in untyped code
```

However, if I require the module inside the evaluator, it all works fine:

``` racket
@(examples
  #:eval ((make-eval-factory #:lang 'typed/racket/base))
  (require typed/alexis/util/comparator)
  (struct foo ())
  (: foo-compare (foo foo -> (U -1 0 1)))
  (define (foo-compare a b) 0)
  (define-comparison-predicates foo : foo foo-compare)
  (foo=? (foo) (foo)))
```

It seems that the way `make-eval-factory` requires the modules isn't compatible with TR. I think the reason for this is explained by this phrase in the documentation:

> each module in mod-paths is also required into the top-level environment for each generated evaluator

The key is "top-level". I suppose the craziness TR does to support the top-level doesn't really work too well with this. Requiring the module manually is a viable workaround, but I wonder if this could be easily fixed (and why it occurs in the first place).

**Comment by bennn** [comment]
The first example runs for me on Racket v6.8
(ok to close this?)
