### ISSUE TITLE
defmethod accepts bogus mode arguments

### ISSUE THREAD

**Issue by LiberalArtist** [racket/scribble#131]
The `defmethod` form silently ignores bad `#:mode` arguments (e.g. `extends` rather than `extend`). It would be nice for it to raise an error, instead.

**Comment by spdegabrielle** [comment]
is this still an issue?  Please consider adding the label `good first issue` so it is findable: 

[Issues labeled `good first issue` in in Racket GitHub repositories](https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22)

**Comment by sorawee** [comment]
I have a fix for this, but needs https://github.com/racket/gui/pull/193 to be merged first.
