### ISSUE TITLE
Why scheme/base and not racket/base?

### ISSUE THREAD

**Issue by soegaard** [racket/scribble#155]
The contents of 
   [scribble/doc/reader.rkt](https://github.com/racket/scribble/blob/master/scribble-lib/scribble/doc/reader.rkt)

is
    #lang scheme/base

Is this on purpose? 
Why not #lang racket/base ?

**Comment by gus-massa** [comment]
Already fixed in https://github.com/racket/scribble/commit/c87989deea02980a94fc1b970bf91351469611f2
