### ISSUE TITLE
What's the use case for enforcing heading levels continuity?

### ISSUE THREAD

**Issue by thblt** [racket/scribble#175]
In Scribble, starting a first part of depth > 0 or an header whose depth is > the containing part's depth +1 fails with an error:

```
decode: misplaced part (the part is more than one layer deeper than its container); title: ("General introduction") context...:
```

There's an example Scribble document triggering the error at the end of this issue.

I'm currently investigating Scribble and other programmable document formats, and I'm mostly interested in book-length documents.  For this use case, it is not unusual:

 - to start a document with a level 2 heading (a chapter), for a preface, introduction or acknowledgments, before emitting a level 1 heading for part 1.

 - to skip a heading level for shorter parts.  For example, all chapters may have \paragraphs, but not all need sections, and sometimes the first \paragraph may appear before the first section.

My question is: does Scribble actually require that the document tree starts at the higher level and never skips levels?  And if this is not strictly required, would you accept a PR to add an optional switch (either as a command line argument, or from the document) to disable the rule?

Thanks!

**Comment by thblt** [comment]
Sorry, forgot the example:

``` 
#lang scribble/book

@subsection{General introduction} 
@section{Part 1}
@subsection{Subsection 2}
@subsection{Subsection 3}
@subsection{Subsection 4}
```

**Comment by mflatt** [comment]
The underlying representation of a document with subsections involves `part` structures nested in `part` structures. So, it needs all parent layers in the end.

Intermediate `part` layers could be synthesized, giving each synthesized one a `'hidden` style property. I think it's probably better for a document author to write an explicit `'hidden` layer to declare the intent. An explicit error when I accidentally skipped a level has often saved me trouble.

**Comment by thblt** [comment]
Thanks for the detailed answer!
