### ISSUE TITLE
Add example (and contract?) for define-footnote

### ISSUE THREAD

**Issue by LeifAndersen** [racket/scribble#19]
Can we add an example to define-footnote to the docs? I have no idea how to use it properly, and the documentation does not make it clear to me. I think Adding an example would help here.

Also, it might make sense to add a contract to define-footnote, because if the footnote-part-id field is not an id, such as in:

```
(define-footnote dynamic-instances-footnote (lambda () @note{Foobar}))
```

the error message leaks the implementation of define-footnote:

  making #path:/Users/leif/src/r-feature-profile/paper/background.scrbl
background.scrbl:86:53: define: not an identifier, identifier with default, or keyword for procedure argument
  at: ()
  in: (define ((lambda () (note "Foobar")) . text) (do-footnote-part footnotes id))
  compilation context...:
   /Users/leif/src/r-feature-profile/paper/background.scrbl
  context...:
   /Users/leif/racket/racket/collects/racket/private/norm-define.rkt:46:33: simple-proto
   /Users/leif/racket/racket/collects/racket/private/norm-define.rkt:134:33: general-proto
   /Users/leif/racket/racket/collects/racket/private/stxloc.rkt:21:17: try-next
   /Users/leif/racket/racket/collects/racket/private/stxloc.rkt:21:17: try-next
   /Users/leif/racket/racket/collects/racket/private/norm-define.rkt:166:4: normalize-definition
   /Users/leif/racket/racket/collects/racket/private/kw.rkt:839:2
   try-next
   /Users/leif/racket/racket/collects/syntax/wrap-modbeg.rkt:46:4
   /Users/leif/racket/racket/collects/compiler/cm.rkt:346:0: compile-zo*
   /Users/leif/racket/racket/collects/compiler/cm.rkt:561:26
   /Users/leif/racket/racket/collects/compiler/cm.rkt:553:42
   /Users/leif/racket/racket/collects/compiler/cm.rkt:518:0: maybe-compile-zo
   /Users/leif/racket/racket/collects/compiler/cm.rkt:633:2: do-check
   /Users/leif/racket/racket/collects/compiler/cm.rkt:672:15
   /Users/leif/racket/racket/collects/compiler/..:113:23: loop
   /Users/leif/racket/racket/collects/compiler/cm.rkt:633:2: do-check

**Comment by jasonhemann** [comment]
At least the example part of this seems to be resolved.

https://github.com/racket/scribble/blob/13798906ceedfc1473643d06f4f98d4f372e889e/scribble-doc/scriblib/scribblings/footnote.scrbl#L35
