### ISSUE TITLE
include-section does not honour book

### ISSUE THREAD

**Issue by pmatos** [racket/scribble#191]
This looks like a bug to me. 

If I have a main book file and then one file for each chapter I define something like:
```
#lang scribble/book

@title{Test}

@table-of-contents{}

@include-section["chap1.scrbl"]
@include-section["chap2.scrbl"]
```

Then chapter 1:
```
#lang scribble/book

@section{This is chapter 1}
```

and chapter 2:
```
#lang scribble/book

@section{This is chap 2}
```

Except that when rendered the chapter numbers are 
```
0.1 This is chapter 1
0.2 This is chap 2
```

If I put the `@section` calls in the main file and drop the `include-section` all looks fine.

**Comment by bennn** [comment]
This happens with any kind of document --- not just books --- because `include-section` shifts everything down one level. Use `@title{This is chapter 1}` etc.

I'm sure this is explained somewhere in the Scribble docs, but I haven't found it yet. Anyway, we should add a note near `include-section`.

**Comment by pmatos** [comment]
@bennn Thanks for the clarification. I am at fault then as I have not read the low level scribble docs yet and somehow missed the getting started guide example. Well, I remember looking at that specific example but my brain was hardwired to think that `include-section` would literally just include a section, so I didn't give it a second thought. Closing.
