### ISSUE TITLE
A section with the tag "index" will overwrite the real "index.html"

### ISSUE THREAD

**Issue by LiberalArtist** [racket/scribble#194]
When rendering multi-page HTML output, Scribble appears to generate the filenames of the section pages by using the section's [*tag*](https://docs.racket-lang.org/scribble/core.html#(tech._tag)) value. Unfortunately, that means that a page beginning with `@title{Index}` will generate "index.html", overwriting the output of the top-level section.

This came up in https://github.com/bbusching/libgit2/issues/3, so you can see the result (for now) by clicking on the link from the [libgit2 package page](https://pkgs.racket-lang.org/package/libgit2), for example.

**Comment by bennn** [comment]
The expected behavior is an error message like this:

```
htmls-render: multiple parts have the same filename (modulo case): #<path:.../index.html>
```

right?

**Comment by jbclements** [comment]
Yep, I noticed this when trying to build libgit2, and in my opinion, an error here would be a great improvement, although it would certainly be nifty to provide a message in this particular case that says "you probably named a file index.scrbl." But... I'm not going to let the perfect be the enemy of the good.
