### ISSUE TITLE
Confusing srcdoc

### ISSUE THREAD

**Issue by sorawee** [racket/scribble#204]
The [doc](https://docs.racket-lang.org/scribble/srcdoc.html) claims that 

> For an example use, see the "file" collection’s "gif.rkt" source file and the corresponding extraction in "scribblings/gif.scrbl". As that example illustrates, starting the module declaration with
>
> #lang at-exp
>
> enables the @-reader, which is handy for writing documentation expressions.

If I'm not mistaken, here's [`scribblings/gif.scrbl`](https://github.com/racket/racket/blob/master/pkgs/racket-doc/file/scribblings/gif.scrbl) of the `file` collection. It also contains `(require scribble/extract)`, showing that it probably is the right file.

But as I read through `scribblings/gif.scrbl`, there's no extraction anywhere that I can see.

`scribblings/gif.scrbl` also mentions functions such as `image-ready-gif-stream?` which is defined in https://github.com/racket/draw/blob/master/draw-lib/file/gif.rkt. Interestingly, https://docs.racket-lang.org/scribble/srcdoc.html claims that this file is written in `#lang at-exp`, but this is certainly not the case.

**Comment by samth** [comment]
Yes, unfortunately that code no longer uses srcdoc. It was removed in https://github.com/racket/draw/commit/46517b9fa1506db7a620fbbf727c9d272d299921 which was when @mflatt reorganized the repository along package lines, and using srcdoc there would (I think) have created some circularity. That documentation should link to another example, but I don't have a suggestion off the top of my head.

**Comment by bennn** [comment]
Is #200 a good substitute?

**Comment by sorawee** [comment]
Yes! But because `gif.rkt` no longer uses srcdoc, that part should be removed.

**Comment by bennn** [comment]
Ok, now srcdoc only points to the submodules blog post

https://blog.racket-lang.org/2012/06/submodules.html
