### ISSUE TITLE
Support for converting values to GIFs

### ISSUE THREAD

**Issue by jackfirth** [racket/scribble#231]
I'd like to write some documentation with example code that includes embedded animations. I assumed I'd be able to do this by making the animations implement the `prop:convertible` interface and support conversion to GIFs. But according to the docs for [`render-convertible-as`](https://docs.racket-lang.org/scribble/core.html?q=special#%28def._%28%28lib._scribble%2Fhtml-properties..rkt%29._render-convertible-as%29%29), it looks like only the PNG and SVG formats are supported. Is GIF support reasonable?

**Comment by spdegabrielle** [comment]
I think this would be a valuable addition. Being able to include animations created with the [record?(2htdp/universe)](https://docs.racket-lang.org/teachpack/2htdpuniverse.html#%28form._world._%28%28lib._2htdp%2Funiverse..rkt%29._record~3f%29%29) sounds like it would provide a nice way to enhance the documentation.
