### ISSUE TITLE
unbound identifier inside quasiquoted hasheq in #lang scribble/lp2

### ISSUE THREAD

**Issue by aymanosman** [racket/scribble#245]
I discovered that his programming does not work.

```
#lang scribble/lp2

@chunk[<main>
       (define foo 42)
       `#hasheq((a . ,foo))]
```

The same issue does NOT occur with a quasiquoted list. So it seems to be something to do with `#hash` syntax.

![Screen Shot 2020-06-13 at 16 30 57](https://user-images.githubusercontent.com/3605049/84572632-4ce38b80-ad93-11ea-9e90-13e729474fe9.png)

**Comment by aymanosman** [comment]
FWIW, a simple workaround I used was to just to define hash's like this:

```racket
(hash 'a foo)
```

Which is arguably easier to read and understand anyway.

**Comment by mflatt** [comment]
Thanks for the report! This is a problem down in the `syntax/strip-context` library, and I'll push a repair.
