### ISSUE TITLE
lp2 error on nearly empty file

### ISSUE THREAD

**Issue by aymanosman** [racket/scribble#249]
I'm not sure how to categorize this admittedly minor bug.

If a file consists of entirely this string `"#lang scribble/lp2"`, with no whitespace at the end of the module path,
then you get a confusing error. The second screenshot shows what I expected (after I added a space to the end of the file).

Seems like it would be really easy to fix.
I'm happy to do it.

![Screen Shot 2020-07-02 at 12 47 31](https://user-images.githubusercontent.com/3605049/86355276-5d847480-bc62-11ea-8eb0-55e6fc47d22a.png)
![Screen Shot 2020-07-02 at 12 47 47](https://user-images.githubusercontent.com/3605049/86355279-5eb5a180-bc62-11ea-943a-2d0adaf5a6d8.png)

**Comment by mflatt** [comment]
Hi @aymanosman - thanks for the report! We'd welcome a PR to fix the problem.
