### ISSUE TITLE
lp2 unbound identifier in quasisyntax

### ISSUE THREAD

**Issue by camoy** [racket/scribble#254]
```rkt
#lang scribble/lp2

@chunk[<everything>
(require (for-syntax racket/base racket/math))
(begin-for-syntax #`#,pi)]
```

Gives an `unbound identifier in: pi` error.  Interestingly, this does not error for quasiquote, only quasisyntax.

**Comment by sorawee** [comment]
I think this is not a bug. You can use [`CHUNK`](https://docs.racket-lang.org/scribble/lp.html?q=chunk#%28form._%28%28lib._scribble%2Flp..rkt%29._.C.H.U.N.K%29%29) so that `unsyntax` is not used for the escape mechanism.

**Comment by camoy** [comment]
Thanks @sorawee, not sure how I missed that form...
