### ISSUE TITLE
Adding txfonts Changes the Font of scribble/acmart

### ISSUE THREAD

**Issue by shhyou** [racket/scribble#271]
The inclusion of `txfonts` in c62d008cfb changes the font of acmart acmsmall articles. Could it be disabled for acmart files?

I am not sure if adding

```
\renewcommand\packageTxfonts\relax
```

to `scribble-lib/scribble/acmart/acmart-load.tex` would be a bad idea or not.

**Comment by rfindler** [comment]
That sounds like the right approach to me. (Of course, there may be other fallout.)
