### ISSUE TITLE
Overly long line

### ISSUE THREAD

**Issue by sorawee** [racket/scribble#304]
<img width="1077" alt="Screen Shot 2021-06-21 at 9 28 38 AM" src="https://user-images.githubusercontent.com/9099577/122796292-10ceea80-d273-11eb-9e8c-25f2b0879118.png">

A line can be overly long. If possible, there should be a line break.

See https://docs.racket-lang.org/canvas-list/index.html for the actual document.

**Comment by rfindler** [comment]
Does it work to add line breaks in the source?

Robby

**Comment by sorawee** [comment]
Yep, thanks!
