### ISSUE TITLE
Add button to toggle TOC column on low-width devices

### ISSUE THREAD

**Issue by jryans** [racket/scribble#313]
Overall, I really enjoy reading documents written with Scribble. 🙂 

The one missing thing for me at the moment is access to the TOC when reading on a low-width device. At the moment, the TOC is hidden with no way to access it.

One path forward would be to add a three lines / hamburger icon somewhere on the page that would allow revealing the TOC when desired, perhaps similar to this version used on [Rust docs](https://docs.rs/env_logger/):

<img src="https://user-images.githubusercontent.com/279572/132110853-32c8fd35-4f46-45d2-b4f6-6af11015a962.png" alt="Screen Shot 2021-09-05 at 01 07 00" width="414">

If other people agree this would be useful, I'm happy to send a PR to implement it. 😄

**Comment by sorawee** [comment]
IMO, this would be very useful! A PR is always welcome :)
