### ISSUE TITLE
Missing license information for LaTeX files

### ISSUE THREAD

**Issue by LiberalArtist** [racket/scribble#332]
The `scribble-lib` package needs additional license information for some LaTeX code it includes. The ones I've found are:

https://github.com/racket/scribble/blob/3866ac350fb703dc64dadaa8c0112ecd163f73a1/scribble-lib/scribble/sigplan/sigplanconf.cls#L3-L24

https://github.com/racket/scribble/blob/3866ac350fb703dc64dadaa8c0112ecd163f73a1/scribble-lib/scribble/scribble.tex#L116-L127

https://github.com/racket/scribble/blob/3866ac350fb703dc64dadaa8c0112ecd163f73a1/scribble-lib/scribble/acmart/acmart.cls#L1-L22

Additionally, it looks like distributing `acmart.cls` requires that `acmart.dtx` be:

> part of the same distribution. (The sources need not necessarily be in the same archive or directory.)

which it doesn't seem like we're doing, though I don't know what the definition of "distribution" is.

I'll try to deal with this unless someone else gets to it first.

I noticed this thanks to [the Debian copyright file](https://metadata.ftp-master.debian.org/changelogs//main/r/racket/racket_8.5+dfsg1-1~bpo11+1_copyright).

**Comment by samth** [comment]
The license for the latest version of acmart is here; it looks a little different: https://github.com/borisveytsman/acmart/blob/primary/acmart.dtx

**Comment by LiberalArtist** [comment]
> The license for the latest version of acmart is here; it looks a little different: https://github.com/borisveytsman/acmart/blob/primary/acmart.dtx

I think the paragraph I quoted may be added by the `docstrip` utility when it generates the `.cls` file from the `.dtx` file. I think it may be referring to this part of [The LaTeX Project Public License](https://www.latex-project.org/lppl.txt):

> 7.  If you are not the Current Maintainer of the Work, you may
> distribute a Compiled Work generated from a Derived Work, as long as
> the Derived Work is distributed to all recipients of the Compiled
> Work, and as long as the conditions of Clause 6, above, are met with
> regard to the Derived Work.

But (while I am not a lawyer) I don't think that's what we're doing, because I don't think we are creating a Derived Work at all. I think what we're doing is covered instead by this provision:

> 3.  You may distribute a Compiled Work that has been generated from a
> complete, unmodified copy of the Work as distributed under Clause 2
> above, as long as that Compiled Work is distributed in such a way that
> the recipients may install the Compiled Work on their system exactly
> as it would have been installed if they generated a Compiled Work
> directly from the Work.

So I don't think we need to distribute any additional files.
