### ISSUE TITLE
Feature request: Anchor links on hover

### ISSUE THREAD

**Issue by typesanitizer** [racket/scribble#341]
It would be nice if this were supported. For example, GitHub supports this in Markdown files with a 🔗 symbol:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/7187503/181819130-bc34ddd2-a137-4d56-9cd3-cf7bd21931ec.png">

There are some answers to this [SO question](https://stackoverflow.com/questions/71045575/hover-on-anchor-link-and-show-icon) which cover how to achieve this. Not 100% sure if those are sufficient or not.

Specifically, the feature request is for:
1. Showing some symbol on hover.
2. The symbol should link to the heading it is next to; the URL can then be copied by right-clicking or by clicking and selecting it from the URL bar.

**Comment by sorawee** [comment]
Fixed by #377.

**Comment by typesanitizer** [comment]
Thanks @sorawee :D
