### ISSUE TITLE
Double underscore renders as single underscore

### ISSUE THREAD

**Issue by countvajhula** [racket/scribble#369]
Example: Qi uses a single underscore to capture a single input value:

```
(~> (2 3) (~a "The numbers are " _ " and " _)) ; => "The numbers are 2 and 3"
```

 and double underscore to capture all input values:

```
(~> (2 3) (~a "The numbers are " __)) ; => "The numbers are 23"
```

In the docs, `__` always appears as `_`. For example, see [Templates and Partial Application](https://docs.racket-lang.org/qi/Qi_Forms.html#%28part._.Templates_and_.Partial_.Application%29). This also happens with the default (rather than manual) CSS style, as we see in [Templates and Partial Application](https://drym-org.github.io/qi/Qi_Forms.html#%28part._.Templates_and_.Partial_.Application%29).

**Comment by soegaard** [comment]
I took a look at the Scribble file. I can see you are using `examples`.
I think, you are running into this:
<img width="775" alt="image" src="https://github.com/racket/scribble/assets/461765/692e2251-e9d8-45c9-948b-de75f30f69d9">
See the last sentence in the docs for `racketblock`.

**Comment by countvajhula** [comment]
Oh wow, can't believe it was that simple. It's been in the docs confusing newbies all this time 😆 
Adding an extra underscore works:

```
@racket[___]
```

I will fix this soon. Thanks @soegaard !

**Comment by countvajhula** [comment]
Hmm, looks like I spoke too soon. It fixes it in places where we simply refer to the form, like `@racket[___]`, but it still breaks in examples because of course there's no identifier called `___`. Might there be a way to escape the escape?

**Comment by sorawee** [comment]
This works for me:

```
@(define my-__ @racketidfont{__})

@examples[
  (eval:alts #, @racket[(quote #,my-__)]  (quote __))
]
```

which produces:

```
Example:      
> '__      
'__
```

Read more about `eval:alts` at the documentation of `examples`.

**Comment by countvajhula** [comment]
This is great. Thank you @sorawee!
