### ISSUE TITLE
Support #:index? in envvar

### ISSUE THREAD

**Issue by sorawee** [racket/scribble#380]
`envvar` should support `#:index?`, which if true, indexes the environment variable for searching.
```[tasklist]
### Tasks
```

**Comment by sorawee** [comment]
A place to utilize this new feature when it's implemented: https://github.com/racket/typed-racket/pull/1341

**Comment by bennn** [comment]
`indexed-envvar` was there all along!
d64e38f732f979ebe30d775b70c7ed1fb55b6774

**Comment by sorawee** [comment]
Do you also want to make the modification mentioned above (https://github.com/racket/typed-racket/pull/1341)?

**Comment by bennn** [comment]
https://github.com/racket/typed-racket/commit/92eff9e9d93c254373460b86316703ab60301875
