### ISSUE TITLE
acmart.cls update

### ISSUE THREAD

**Issue by rfindler** [racket/scribble#409]
It looks like acmart.cls is [now at 2.03](https://www.ctan.org/pkg/acmart) and the [acm site](https://www.acm.org/publications/authors/submissions) has also been updated.

I wonder if there is a way to get alerted when new versions come out?

**Comment by sorawee** [comment]
RSS/Atom is perfect for this: https://www.ctan.org/ctan-ann/atom/acmart.xml

**Comment by rfindler** [comment]
Is the idea that we'd set up a CI job here that can check those feeds from time to time?

**Comment by sorawee** [comment]
What I meant was that if you already use an RSS reader, you can just add it to the reader, and the reader will notify you when there's an update.

But using CI's cron to run every X days could work too, I think.

**Comment by rfindler** [comment]
Oh! I've done that so hopefully I'll notice next time. Thanks!

**Comment by bennn** [comment]
updated classfile to 2.03: 3bdb66a2

**Comment by rfindler** [comment]
Thanks!
