### ISSUE TITLE
acmart and final paper instructions

### ISSUE THREAD

**Issue by rfindler** [racket/scribble#428]
I got the following instructions from conference publishing:

> The ACM style provides the three small sections 'CCS Concepts', 'Additional Key Words and Phrases', and 'ACM Reference Format' to follow the abstract; these are mandatory on the paper in the given order. Make sure you correctly classify your paper using the 2012 ACM Computing Classification System (CCS). The content of the CCS has to be picked from the provided list (with the CCS tool). The order of the CCS concepts is based on their relevance. The keywords are user-defined. (You should also insert the CCS XML snippet into your sources: for LaTeX documents using the environment 'CCSXML' and for Word documents using the properties dialog.)

and I'm not sure how I should be handling this in my `scribble/acmart` paper. I see the `terms` and `keywords` functions, and I tried using them, but I didn't get anything to show up in the genreated PDF. Does someone know how to do this? (Once I understand, I can help improve the docs.)

**Comment by bennn** [comment]
The final Rhombus paper has those 3 sections, so I guess you want `@ccsdesc` and `@keywords` like it has:
https://github.com/mflatt/rhombus-paper/blob/main/paper.scrbl

Maybe the sections don't appear because there's a `\settopmatter` command somewhere that's turning them off? Rhombus paper did that at some early point:
```
\settopmatter{printfolios=true,printccs=false,printacmref=false}
```
https://github.com/mflatt/rhombus-paper/blob/3c953eac893a2861b4c8dde7c28f3c5a772104ea/style.tex#L14

**Comment by rfindler** [comment]
Ah, I see how `keywords` and `ccsdesc`, works, thanks! I've pushed a clarification of the docs. 

I didn't manage to get the "ACM Reference format" to appear. And it looks like the rhombus paper doesn't build anymore.

**Comment by rfindler** [comment]
I'm going to close this issue now. It looks like the reason I didn't get the "ACM Reference Format:" section was because I put "nonacm" and I put that because of some advice in the PDF itself saying "Please use nonacm option or ACM Engage class to enable CC licenses" where, it appears, I took the wrong branch of that "or". I'll need to figure out what "ACM Engage class" is, I suppose, and if I find something to put in the docs, I'll do that.
