### ISSUE TITLE
How to open and build Scribble project?

### ISSUE THREAD

**Issue by Ju2ender** [racket/scribble#60]
Hi there

How to open and build Scribble project?

**Comment by bennn** [comment]
You can open Scribble projects the same way as Racket projects.
To build a Scribble project called `file.scrbl`, run `scribble file.scrbl`.

The Scribble "Getting Started" guide has a few examples:
http://docs.racket-lang.org/scribble/getting-started.html

**Comment by Ju2ender** [comment]
Thanks bennn. :)
