### ISSUE TITLE
Margin notes overlap

### ISSUE THREAD

**Issue by leafac** [racket/scribble#66]
**PRE-CONDITIONS**

1. The screen is large enough that the margin notes appear on the margin instead of interspersed in the text.

2. There are two margin notes too near to one another.

**CURRENT BEHAVIOR**

The margin notes overlap, making the text unreadable:

![demand-driven_program_analysis](https://cloud.githubusercontent.com/assets/586813/20315581/79c85382-ab2c-11e6-9fff-2d85ff084ae8.png)

**EXPECTED BEHAVIOR**

The second margin note goes under the first margin note, with no overlap.

**SUGGESTED SOLUTION**

[Tufte CSS](https://edwardtufte.github.io/tufte-css/) has the behavior I expect. It achieves it by a [small hack](https://github.com/edwardtufte/tufte-css/blob/gh-pages/tufte.css#L162-L164): `float: right; clear: right; margin-right: -<width>;`.

-------

If you agree this is an issue I can work on a Pull Request.

**Comment by leafac** [comment]
In particular, I ask for @mbutterick’s feedback, since he was the creator of the stylesheet I’m proposing to change.

**Comment by mbutterick** [comment]
I agree it’s a defect. I could never figure out how to fix it. Of course, you should test this patch to make sure it does what you think it will. I believe it should go in [`manual-style.css`](https://github.com/racket/scribble/blob/master/scribble-lib/scribble/manual-style.css#L356).
