### ISSUE TITLE
Handling of permissions for `manual-fonts.css` etc. changed?

### ISSUE THREAD

**Issue by jsmaniac** [racket/scribble#69]
I just updated my minimal racket installation from 6.7.0.1 to 6.7.0.3, and I noticed that `raco setup --avoid-main` gives an error, saying that it can't overwrite the `manual-fonts.css` `manual-racket.css` etc. files.

I checked their permissions, and it seems that all these files were `-r--r--r--` for all packages (both those in ~/.racket from the catalog, and the linked packages). After doing
```find /home/georges/.racket/ -name doc -print0 | xargs -0 chmod +w -R```
and re-running `raco setup --avoid-main`, the new files correctly have the mode `-rw-r--r--`.

Is it possible that earlier versions placed the files with read-only attributes, and that the new version refuses to overwrite read-only files? Unless I'm mistaken, the directory itself is writable, so scribble could in principle remove the read-only files and replace them by the new ones.

**Comment by mbutterick** [comment]
It’s possible. I recently replaced the fonts with new versions (#64). I'll look into this further.

**Comment by mflatt** [comment]
I think there are one or two bugs here:

 * `raco setup` shouldn't try to update the file if `--avoid-main` is specified

 * `copy-file` in ok-to-replace mode should maybe use `'truncate/replace` instead of `'truncate`

I hope to take a closer look soon.

**Comment by mflatt** [comment]
Meanwhile, it could be useful to know whether the crash in 64-bit mode happens during the body of "gui-lib/mred/private/wx/cocoa/queue.rkt". Does adding `log-error` to the end of that module show that it's reached?

**Comment by jsmaniac** [comment]
In this case, the packages were installed in `~/.racket`, and the problem occurred for my own "linked" packages too, which should definitely be updated even when `--avoid-main` is specified.

**Comment by mflatt** [comment]
@jsmaniac Thanks for the clarification; I see that I misread the report, and it's not about main-installation files.

I looked into making `copy-file` delete and recreate if replacing a file's content fails, but I'm reluctant to make `copy-file` behave differently than Windows's `CopyFile` function. I'll just change `raco setup` to explicitly delete a file that it wants to replace.
