### ISSUE TITLE
acmart does not export include-abstract

### ISSUE THREAD

**Issue by mfelleisen** [racket/scribble#93]
. . . but it is in the docs.

**Comment by bennn** [comment]
Similar issue: abstracts defined with `@abstract{...}` do not appear in documents.

The problem is,

> The environment `abstract` must appear before `\maketitle`

in acmart.cls. See page 15 in http://ctan.sharelatex.com/tex-archive/macros/latex/contrib/acmart/acmart.pdf

**Comment by bennn** [comment]
closed by #160
