### ISSUE TITLE
Numberers are not displayed as a prefix of their children's numbers (in HTML)

### ISSUE THREAD

**Issue by jsmaniac** [racket/scribble#96]
When rendered with `raco scribble --html file.scrbl`, the scribble file below produces the following table of contents:

```
    A SecA
      1 SubAA
        1.1 SubAAA
        1.2 SubAAB
      2 SubAB
        2.1 SubABA
        2.2 SubABB
    B SecB
    C SecC
```

I would expect the parent number to show up as a prefix of the subsections, so that `SubAA` would be numbered as `A.1`, and `SubAAA` would be numbered as `A.1.1`, and so on. This is the behaviour when no numberer is used, but as soon as a numberer is specified, the parent numbers stop appearing as part of the children numbers.

```
#lang scribble/manual
@require[scribble/core]
@(define my-numberer
   (make-numberer (λ (current parents)
                    (values (list-ref '("A" "B" "C" "D" "…")
                                      (sub1 current))
                            (add1 current))) 1))
@title{Foo}
@(table-of-contents)
@section[#:style (style #f (list my-numberer))]{SecA}
@subsection{SubAA}
@subsubsection{SubAAA}
@subsubsection{SubAAB}
@subsection{SubAB}
@subsubsection{SubABA}
@subsubsection{SubABB}
@section[#:style (style #f (list my-numberer))]{SecB}
@section[#:style (style #f (list my-numberer))]{SecC}
```

**Comment by jsmaniac** [comment]
This seems to be a documentation issue, not an actual bug.

The documentation for [`part-number-item?`](http://docs.racket-lang.org/scribble/core.html#%28def._%28%28lib._scribble%2Fcore..rkt%29._part-number-item~3f%29%29) says:

> Return #t if v is #f, an exact non-negative integer, a string, or a list containing two strings. See part for information on how different representations are used for numbering.

It seems that when the numberer returns a list of two strings, the first is treated as the section's number, and the second as a separator, and these are used as prefixes on children's strings.

The documentation for [`part`](http://docs.racket-lang.org/scribble/core.html#%28def._%28%28lib._scribble%2Fcore..rkt%29._part%29%29) does not contain anything on that topic, however, and neither does the documentation for [`make-numberer`](http://docs.racket-lang.org/scribble/core.html#%28def._%28%28lib._scribble%2Fcore..rkt%29._make-numberer%29%29). Also, it seems best to document this inside `part-number-item?` or `make-numberer`, and refer to those from `part`, rather than the opposite (rationale: the documentation for part is already pretty large, and having to find the relevant information within will make that information less easy to access/read).

**Comment by mflatt** [comment]
Thanks – I followed the same dead-ends in the docs while trying to sort this out. It turns out that the information is in the docs for `collected-info`. I'll work on the docs and cross-referencing.

**Comment by jsmaniac** [comment]
Thanks!
