### ISSUE TITLE
Scribble will split @racket[...] identifiers down the middle.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/scribble#99]
If I have the following scribble program:

```
#lang scribble/sigplan

@require[scribble/manual]

Paragraph
@racket[(some-racket-function name with arguments)]. This
paragraph also has a bunch of text so that we can get a good
sense of what the fill box is.
```

When I render it to a pdf, the `arguments` identifier gets split across to a new line, making:

![screen shot 2017-04-03 at 5 03 05 pm](https://cloud.githubusercontent.com/assets/285926/24631734/70573b76-188f-11e7-9855-1403e55dd5bf.png)

I get that a chunk of `@racket[...]` code is in the text and might wrap, but splitting it in the middle of an identifier like this seems bad.

**Comment by jeapostrophe** [comment]
In particular, it makes it seem like the argument is "ar-guments" which could be bad if a function name were rendered wrong, etc.

Leif, can you check where the - is inserted? Is it by the LaTeX backend? If so, we could put code blocks in `\nohyphens{}`

**Comment by LeifAndersen** [comment]
I strongly suspect its inserted by latex, and I'll see if is fixable. I agree that something like `\nohyphens{}` is the right way to go about fixing this.

**Comment by LeifAndersen** [comment]
Also, given that the file expands to the following tex code, I think its safe to say that its latex inserting it:

```
Paragraph
\RktPn{(}\RktSym{some{-}racket{-}function}\Scribtexttt{ }\RktSym{name}\Scribtexttt{ }\RktSym{with}\Scribtexttt{ }\RktSym{arguments}\RktPn{)}. This
paragraph also has a bunch of text so that we can get a good
sense of what the fill box is.
```

**Comment by LeifAndersen** [comment]
Okay, adding `\nohyphens{}` causes the output to be:
![screen shot 2017-04-03 at 6 18 29 pm](https://cloud.githubusercontent.com/assets/285926/24634102/009434dc-189a-11e7-96f3-6672d459df02.png)

At least no hyphens are created, although I wish it would take the identifier to the next line.

**Comment by LeifAndersen** [comment]
Moving conversation to PR #100
